import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const toAbsolute = (p) => path.resolve(__dirname, p)

async function prerender() {
  console.log('🚀 Starting Pre-rendering (SSR)...')

  // 1. Load the template index.html generated by the client build
  const templatePath = toAbsolute('dist/index.html')
  if (!fs.existsSync(templatePath)) {
    throw new Error('❌ Client build index.html not found! Run npm run build first.')
  }
  const template = fs.readFileSync(templatePath, 'utf-8')

  // 2. Import the compiled server-side render function
  const serverEntryPath = toAbsolute('dist/server/entry-server.js')
  if (!fs.existsSync(serverEntryPath)) {
    throw new Error('❌ Server build entry-server.js not found! Run SSR build first.')
  }
  
  // Dynamic import of the built server module
  const { render } = await import(serverEntryPath)

  // 3. Render the app's HTML on the server
  const { html } = render()

  // 4. Inject the pre-rendered HTML into the root div
  const htmlWithPrerender = template.replace(
    `<div id="root"></div>`,
    `<div id="root">${html}</div>`
  )

  // 5. Overwrite the index.html with the pre-rendered content
  fs.writeFileSync(templatePath, htmlWithPrerender, 'utf-8')
  console.log('✅ Pre-rendering complete! dist/index.html successfully updated.')

  // 6. Clean up temporary server build directory
  try {
    fs.rmSync(toAbsolute('dist/server'), { recursive: true, force: true })
    console.log('🧹 Cleaned up temporary server build files.')
  } catch (err) {
    console.warn('⚠️ Could not remove dist/server directory:', err.message)
  }
}

prerender().catch((err) => {
  console.error('❌ Pre-rendering failed:', err)
  process.exit(1)
})
